name: fin-dl-benchmark
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pyyaml
  - jupyter
  - ipykernel
  - statsmodels
  - networkx
  - pip:
    - yfinance
    # Optional mamba installation
    # - mamba-ssm
